/**
 * ShadowSwap Frontend Configuration
 * 
 * Imports deployment addresses from config.json (auto-generated by deployment script).
 */

// @ts-ignore - JSON import
import deployment from './config.json';

// ============ Backend Configuration ============
export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:3000';

// ============ Chain Configuration ============
export const CHAIN_ID = 11155111; // Sepolia
export const CHAIN_NAME = 'Sepolia';

// ============ Contract Addresses (from deployment) ============

/** ShadowHook contract address (deployed via HookMiner) */
export const HOOK_ADDRESS = deployment.hookAddress as `0x${string}`;

/** ShadowRouter contract address (handles fund transfers for swaps) */
export const ROUTER_ADDRESS = deployment.routerAddress as `0x${string}`;

/** Mock token deployed during hook deployment */
export const MOCK_TOKEN = deployment.mockTokenAddress as `0x${string}`;

/** Backend solver wallet address */
export const SOLVER_ADDRESS = deployment.solverAddress as `0x${string}`;

/** Uniswap v4 PoolSwapTest Router on Sepolia (legacy - use ROUTER_ADDRESS instead) */
export const POOL_SWAP_TEST = '0x9b6b46e2c869aa39918db7f52f5557fe577b6eee' as const;

/**
 * Uniswap v4 PoolManager on Sepolia
 * Source: https://docs.uniswap.org/contracts/v4/deployments
 */
export const POOL_MANAGER_ADDRESS = deployment.poolManagerAddress as `0x${string}` || '0xE03A1074c86CFeDd5C142C4F04F1a1536e203543';

// Legacy alias for backward compatibility
export const MOCK_TOKEN_ADDRESS = MOCK_TOKEN;

/** Mock ENS Resolver address for Audit Trail */
export const MOCK_ENS_ADDRESS = deployment.mockENSAddress as `0x${string}`;

// ============ Pool Key Configuration ============

/**
 * Pool Key Object from deployment
 */
export const POOL_KEY = {
  currency0: deployment.poolKey.currency0 as `0x${string}`,
  currency1: deployment.poolKey.currency1 as `0x${string}`,
  fee: deployment.poolKey.fee,
  tickSpacing: deployment.poolKey.tickSpacing,
  hooks: HOOK_ADDRESS,
} as const;

// ============ Supported Tokens ============
// Token metadata for the UI

export interface Token {
  address: string;
  symbol: string;
  name: string;
  decimals: number;
  logoURI?: string;
}

export const TOKENS: Record<string, Token> = {
  ETH: {
    address: '0x0000000000000000000000000000000000000000',
    symbol: 'ETH',
    name: 'Ethereum',
    decimals: 18,
    logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
  },
  SHADOW: {
    address: MOCK_TOKEN_ADDRESS,
    symbol: 'SHADOW',
    name: 'ShadowSwap Test Token',
    decimals: 18,
    logoURI: undefined,
  },
};

// ============ Yellow Network Configuration ============
export const YELLOW_NETWORK = {
  sandbox: 'wss://clearnet-sandbox.yellow.com/ws',
  production: 'wss://clearnet.yellow.com/ws',
} as const;

// ============ API Endpoints ============
export const API = {
  submitIntent: `${BACKEND_URL}/submit-intent`,
  getIntents: `${BACKEND_URL}/intents`,
  health: `${BACKEND_URL}/health`,
} as const;

// ============ UI Configuration ============
export const UI_CONFIG = {
  // Slippage tolerance options (in basis points)
  slippageOptions: [50, 100, 200, 500], // 0.5%, 1%, 2%, 5%
  defaultSlippage: 100, // 1%

  // Intent expiry time (in seconds)
  intentExpiryTime: 300, // 5 minutes

  // Polling interval for intent status (in ms)
  statusPollingInterval: 3000,
} as const;
